version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB:-ecom}
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # override URI to point at the mongo container
      MONGO_URI: mongodb://mongo:27017/${MONGO_DB:-ecom}
    depends_on:
      - mongo
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    environment:
      # inside Docker, point at the backend container
      NEXT_PUBLIC_BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongo-data:
